token: 53e54ca5bfbf325a57d24562f86d7c352ca202b8
ipHome: 192.168.222.110
ip: 192.168.1.14
port: 9998
heating:
  sensorId: 67
  heaterId: 998
mariaDB:
  user: root
  password: admin
  ip: 192.168.222.240
  port: 3306
  database: domotique
  logs: logs
  stats: domotiqueStats
charsToRemove:
  - from: é
    to: e
  - from: à
    to: a
  - from: ç
    to: c
  - from: è
    to: e
  - from: ê
    to: e
  - from: ö
    to: o
  - from: à
    to: a
  - from: ë
    to: e
  - from: ô
    to: o


