token: 53e54ca5bfbf325a57d24562f86d7c352ca202b8
ip: 192.168.222.5
port: 9998
heating:
  sensorId: 82
  heaterId: 72
mariaDB:
  user: root
  password: admin
  ip: 192.168.222.55
  port: 3306
  database: domotique
  logs: logs
  stats: domotiqueStats
charsToRemove:
  - from: é
    to: e
  - from: à
    to: a
  - from: ç
    to: c
  - from: è
    to: e
  - from: ê
    to: e
  - from: ö
    to: o
  - from: à
    to: a
  - from: ë
    to: e
  - from: ô
    to: o


